GET http://localhost:1080/simpleSecond
Accept: application/json

###
GET http://localhost:1080/simpleFirst
Accept: application/json

###
POST http://localhost:1080/login
Content-Type: application/json

{
  "username": "foo",
  "password": "bar"
}

###